import { signIn } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>rhettalerts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <span className={styles.logo}>
          <Image src="/RhettAlertLogov2.png" alt="RhettAlert Logo" width={400} height={400} />
        </span>
      </div>
      <div className={styles.container1}>
        <button className={styles.btn}
          onClick={() => signIn(undefined, { callbackUrl: "/dashboard" })} // Log in
        >
          Login
        </button>
      </div>
      
    </div>
  );
}
